version: '3'

services:
  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: faro
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    volumes:
      - ./docker/mariadb_data:/var/lib/mysql
      # DB structure and data
      - ./docker/db_scripts:/docker-entrypoint-initdb.d

volumes:
  mariadb_data:
    driver: local
