version: '3'

services:
  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: faro
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    volumes:
      # DB structure and data
      - ./docker/db_scripts:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: user
      PMA_PASSWORD: 1234
    ports:
      - "8080:80"

volumes:
  mariadb_data:
    driver: local