-- MySQL Script generated by MySQL Workbench
-- dom 17 mar 2024 19:27:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema faro
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `faro` ;

-- -----------------------------------------------------
-- Schema faro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `faro` ;
USE `faro` ;

-- -----------------------------------------------------
-- Table `faro`.`users_profiles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `faro`.`users_profiles` ;

CREATE TABLE IF NOT EXISTS `faro`.`users_profiles` (
  `user_profile_id` BINARY(16) NOT NULL,
  `users_profile_profile_picture` BLOB NULL,
  `user_profile_headline` VARCHAR(128) NOT NULL,
  `user_profile_description` VARCHAR(512) NULL,
  `user_profile_ocupation_status` ENUM('Working', 'Studying', 'Loking for a job') NULL,
  PRIMARY KEY (`user_profile_id`));


-- -----------------------------------------------------
-- Table `faro`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `faro`.`users` ;

CREATE TABLE IF NOT EXISTS `faro`.`users` (
  `user_id` BINARY(16) NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `user_first_surname` VARCHAR(45) NOT NULL,
  `user_second_surname` VARCHAR(45) NULL,
  `user_email` VARCHAR(254) NOT NULL,
  `user_password` VARCHAR(60) NOT NULL,
  `user_role` ENUM('admin', 'teacher', 'company', 'student') NOT NULL,
  `users_profiles_user_profile_id` BINARY(16) NOT NULL,
  PRIMARY KEY (`user_id`, `users_profiles_user_profile_id`),
  UNIQUE INDEX `user_email_UNIQUE` (`user_email` ASC) VISIBLE,
  INDEX `fk_users_users_profiles_idx` (`users_profiles_user_profile_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_users_profiles`
    FOREIGN KEY (`users_profiles_user_profile_id`)
    REFERENCES `faro`.`users_profiles` (`user_profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `faro`.`users_publications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `faro`.`users_publications` ;

CREATE TABLE IF NOT EXISTS `faro`.`users_publications` (
  `user_publication_id` BINARY(16) NOT NULL,
  `user_publication_msg` VARCHAR(2048) NOT NULL,
  `users_publications_created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `users_user_id` BINARY(16) NOT NULL,
  `users_users_profiles_user_profile_id` BINARY(16) NOT NULL,
  PRIMARY KEY (`user_publication_id`, `users_user_id`, `users_users_profiles_user_profile_id`),
  INDEX `fk_users_publications_users1_idx` (`users_user_id` ASC, `users_users_profiles_user_profile_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_publications_users1`
    FOREIGN KEY (`users_user_id` , `users_users_profiles_user_profile_id`)
    REFERENCES `faro`.`users` (`user_id` , `users_profiles_user_profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `faro`.`users_direct_messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `faro`.`users_direct_messages` ;

CREATE TABLE IF NOT EXISTS `faro`.`users_direct_messages` (
  `user_direct_message_msg` VARCHAR(1024) NOT NULL,
  `user_direct_message_sender` BINARY(16) NOT NULL,
  `user_direct_message_receiber` BINARY(16) NOT NULL,
  `users_user_id` BINARY(16) NOT NULL,
  `users_users_profiles_user_profile_id` BINARY(16) NOT NULL,
  PRIMARY KEY (`user_direct_message_receiber`, `user_direct_message_sender`, `users_user_id`, `users_users_profiles_user_profile_id`),
  INDEX `fk_users_direct_messages_users1_idx` (`users_user_id` ASC, `users_users_profiles_user_profile_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_direct_messages_users1`
    FOREIGN KEY (`users_user_id` , `users_users_profiles_user_profile_id`)
    REFERENCES `faro`.`users` (`user_id` , `users_profiles_user_profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;